from __future__ import annotations

import argparse
import sys

from bolt8.config import PROFILES
from bolt8.engine import Bolt8Engine, decode_bytes, encode_bytes
from bolt8.gguf import parse_gguf_header


def main(argv: list[str] | None = None) -> int:
    # Windows consoles often use a legacy code page (cp1252); generated bytes can
    # decode to characters it cannot encode. Never let print() kill the run.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(errors="replace")
    p = argparse.ArgumentParser(prog="bolt8", description="Bolt8 consumer-GPU MoE runtime")
    sub = p.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("bench", help="measure decode tok/s")
    b.add_argument("--profile", default="200b", choices=list(PROFILES))
    b.add_argument("--tokens", type=int, default=32)
    b.add_argument("--warmup", type=int, default=4)
    b.add_argument("--full-route", action="store_true", help="route over CPU-resident experts too")
    b.add_argument("--no-host-experts", action="store_true", help="skip allocating RAM experts")

    g = sub.add_parser("generate", help="greedy generate from a prompt")
    g.add_argument("--profile", default="debug", choices=list(PROFILES))
    g.add_argument("--prompt", default="Hello")
    g.add_argument("--max-new", type=int, default=32)

    i = sub.add_parser("info", help="print profile math or GGUF header")
    i.add_argument("--profile", default="200b", choices=list(PROFILES))
    i.add_argument("--gguf", default=None)

    args = p.parse_args(argv)

    if args.cmd == "info":
        cfg = PROFILES[args.profile]
        print(cfg.summary())
        print(f"  moe_params={cfg.moe_params/1e9:.2f}B attn={cfg.attn_params/1e9:.2f}B")
        print(f"  packed_expert_bytes={cfg.packed_expert_bytes/1e9:.2f}GB")
        if args.gguf:
            hdr = parse_gguf_header(args.gguf)
            print(f"GGUF v{hdr['version']} tensors={len(hdr['tensors'])} kv={len(hdr['kv'])}")
            for t in hdr["tensors"][:12]:
                print(f"  {t['name']} {t['dims']} type={t['type']}")
        return 0

    if args.cmd == "bench":
        print(PROFILES[args.profile].summary())
        eng = Bolt8Engine(
            args.profile,
            allocate_experts=True,
            allocate_cpu=not args.no_host_experts,
            gpu_experts_only=not args.full_route,
        )
        res = eng.bench(tokens=args.tokens, warmup=args.warmup)
        print(res.as_text())
        if res.tps < 5:
            print("below 5 tok/s target", file=sys.stderr)
        return 0

    if args.cmd == "generate":
        eng = Bolt8Engine(args.profile)
        ids = encode_bytes(args.prompt, eng.cfg.vocab_size)
        out = eng.generate_ids(ids, max_new=args.max_new)
        print(decode_bytes(out))
        return 0

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
